---
- name: Testing our new role
  hosts: localhost
  connection: local
  gather_facts: yes # we need this in order to complete our prechecks

  collections:
          - acmeinc.middlewear

  tasks:
          - name: run our generic linux prechecks
            include_role:
                    name: linux-prechecks
