---
- name: Testing my new module
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Testing my custom module to interact with NASA imagery and Google Earth
    nasaimagery:
      lon: -95.33
      lat: 29.78
      apikey: DEMO_KEY # replace with your key
      dest: /home/student/static/example.png   # location to download image

