---
# tasks file for linux-prechecks
# platforms that you might automate against
# EL7, EL8, AIX, SOLARIS, CENTOS, UBUNTU 18

# prechecks on RHEL
- include_tasks: setup-redhat-7.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == "7" 

- include_tasks: setup-redhat-8.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == "8"

# prechekcs on centos
- include_tasks: setup-centos-6.yml
  when:
      - ansible_distribution == "CentOS"
      - ansible_distribution_major_version == "6"

# prechecks on Ubuntu
- include_tasks: setup-ubuntu-18.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == "18"
