---
# a series of asserts which ensure our state modifications of our ubuntu platform will be successful
- name: Precheck - check for total memory on platform
  assert:
          that: ansible_memtotal_mb > 500   # ensure the target has more than 500 mb of ram

- name: Precheck - check for avail block on platform
  assert:
          that: ansible_mounts[0].block_available >= 3000000

# ensure we (at least) python 3.6 is installed on the remote hosts
# for example, RHEL 5 won't have this, but theres no reason that ubutnu 18.04 shouldn't
- name: Precheck - check python version
  assert:
          that: ansible_python.version.major >= 3 and ansible_python.version.minor >= 6
